services:
  app:
    build: .
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["poetry", "run", "streamlit", "run", "src/app.py", "--server.port", "8080"]
  test:
    build: .
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - .:/app
    command: ["poetry", "run", "pytest", "tests/test.py"]
  api:
    build: .
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["poetry", "run", "uvicorn", "--host", "0.0.0.0", "--port", "8080", "api.api:app"]

